require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

RSpec/MultipleExpectations:
  Max: 4

RSpec/ExampleLength:
  Max: 10

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false